name: CI/CD Development Deploy

on:
  # push:
  #   branches:
  #     - development
  pull_request:
    branches: [master]

jobs:
  firebase-test-and-stage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm run test
      - run: npm run build

      
