name: CI/CD Development Deploy

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12.x"
        name: "Test Suite"
      - working-directory: ./frontend
      - run: npm install
      - run: npm run test

      
